apiVersion: v1
kind: Secret
metadata:
  name: rust10x-db-secret
  namespace: rust10x-web-app
type: Opaque
immutable: true
stringData:
  SERVICE_DB_URL: "postgres://app_user:dev_only_pwd@rust10x-db:5432/app_db"
  SERVICE_PG_ROOT_URL: "postgres://postgres:welcome@rust10x-db:5432/postgres"
