apiVersion: v1
kind: Secret
metadata:
  name: rust10x-postgres-secret
  namespace: rust10x-web-app
type: Opaque
stringData:
  POSTGRES_DB: app_db
  POSTGRES_USER: app_user
  POSTGRES_PASSWORD: dev_only_pwd
  POSTGRES_ROOT_PASSWORD: welcome
