apiVersion: v1
kind: Service
metadata:
  labels:
    run: rust10x-web-server
  name: rust10x-web-server-srv
  namespace: default
spec:
  ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: rust10x-web-server
  type: LoadBalancer
---

