apiVersion: v1
kind: Service
metadata:
  labels:
    run: zeroflux-web-server
  name: zeroflux-web-server-srv
  namespace: default
spec:
  ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: zeroflux-web-server
  type: LoadBalancer
---

