apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust10x-web-server-dep
  namespace: default
  labels:
    run: rust10x-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rust10x-web-server
  template:
    metadata:
      labels:
        run: rust10x-web-server
    spec:
      volumes:
        - name: rust10x-web-server-sql
          hostPath:
            path: "/mnt/sql"
            type: Directory
        - name: rust10x-web-server-web-folder
          hostPath:
            path: "/mnt/web-folder"
            type: Directory
        - name: rust10x-web-server-entrypoint
          hostPath:
            path: "/mnt/crates/services/web-server/entrypoint.sh"
            type: File
        - name: rust10x-web-server-bin
          hostPath:
            path: "/mnt/rs-builder/rs-builder-target/web-server"
            type: File
      containers:
        - image: debian:bullseye-slim
          name: rust10x-web-server-ctn
          imagePullPolicy: Always
          env:
            - name: service_name
              value: rust10x-web-server
          command:
            [
              "/bin/bash",
              "-c",
              "source ~/.bashrc && /service/entrypoint.sh ${@}",
              "--",
            ]
          volumeMounts:
            - mountPath: /service/sql
              name: rust10x-web-server-sql
            - mountPath: /service/entrypoint.sh
              name: rust10x-web-server-entrypoint
            - mountPath: /service/web-server
              name: rust10x-web-server-bin
            - mountPath: /service/web-folder
              name: rust10x-web-server-web-folder
          workingDir: /service
      restartPolicy: Always
