apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeroflux-web-server-dep
  namespace: default
  labels:
    run: zeroflux-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zeroflux-web-server
  template:
    metadata:
      labels:
        run: zeroflux-web-server
    spec:
      containers:
        - image: "{{registry}}/zeroflux-web-server:{{image_tag}}"
          name: zeroflux-web-server-ctn
          imagePullPolicy: Always
          env:
            - name: service_name
              value: zeroflux-web-server
      restartPolicy: Always
