apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-web-server-dep
  namespace: default
  labels:
    run: sse-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sse-web-server
  template:
    metadata:
      labels:
        run: sse-web-server
    spec:
      containers:
        - image: "192.168.0.104:5000/zeroflux-sse-web-server:KDD-EXAMPLE"
          name: sse-web-server-ctn
          imagePullPolicy: Always
          env:
            - name: service_name
              value: sse-web-server
      restartPolicy: Always
