apiVersion: v1
kind: Service
metadata:
  name: rust10x-web-server
  namespace: rust10x-web-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: rust10x-web-server
