apiVersion: v1
kind: ConfigMap
metadata:
  name: rust10x-config
  namespace: rust10x-web-app
data:
  SERVICE_TOKEN_DURATION_SEC: "1800"
  SERVICE_WEB_FOLDER: web-folder/
  SERVICE_SQL_FOLDER: /service/sql/
